version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
          - echo Installing dependencies...

    pre_build:
        commands:
          - echo "we are in the pre build phase"
    
    build:
        commands:
          - echo Building the application...
          - ls -l
    
    post_build:
        commands:
          - echo Build completed on `date`
          - echo Preparing artifacts...

artifacts:
  files:
    - '*'
  discard-paths: no

