version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
          - echo Installing dependencies...

    pre_build:
        commands:
          - echo Listing all files in repository...
          - ls -l
          
    build:
        commands:
          - echo Preparing all repository files for artifact...
          - mkdir -p build  # Create output directory
          - cp -r ./* build/  # Copy all files and directories to build directory

    post_build:
        commands:
          - echo Artifact preparation completed on `date`

artifacts:
  files:
    - '**/*'  # Include all files and directories
  base-directory: 'build'  # Output directory for artifacts
  discard-paths: no
